language: android
jdk: oraclejdk8

branches:
  except:
    - build
    
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

env:
  global:
    - ANDROID_API=24
    - EMULATOR_API=21
    - ANDROID_BUILD_TOOLS=24.0.2
    - ADB_INSTALL_TIMEOUT=5 # minutes
    - test=1234
 
android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - android-21
    - android-19
    - extra-google-m2repository
    - extra-android-m2repository # for design library
    - addon-google_apis-google-19 # google play services
    # - sys-img-armeabi-v7a-addon-google_apis-google-24
    # - sys-img-armeabi-v7a-addon-google_apis-google-21
    # - sys-img-armeabi-v7a-android-24
    # - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-19
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
 
before_install:
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
    - chmod 777 ./gradlew
    - ./gradlew dependencies || true

before_script:
    # - android list targets
    - echo no | android create avd -n test -t android-19 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &

script:
    - "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"
    #- git config credential.helper "store --file=.git/credentials"
    #- git config --global user.email "travis@ci.com"
    #- git config --global user.name "BuildBot"
    #- git add -f *
    #- git commit -m "travis build"
    #- echo "https://${access_token}:@github.com" > .git/credentials
    #- git push -u origin master:build
